[package]
name = "webserver"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.9"
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread"] }
log = "0.4.22"
colog = "1.3.0"
config = "0.15.4"
